config/routes.rb
Rails.application.routes.draw do
  root :to => "home#index"
  get 'home/index'
  
  # get 'user_sessions/new'
  # get 'user_sessions/create'
  # get 'user_sessions/destroy'
  resources :categories
  resources :posts
  resources :user_sessions
  resources :users



  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  
  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  has_many :posts
  accepts_nested_attributes_for :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :fonticon)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @home = true
    @categories = Category.all
    @posts = Post.all.limit(4)
    @allPosts = Post.order(:updated_at => :desc)
    @evenPosts = @allPosts.where("id % 2 = 0").limit(5)
    @oddPosts = @allPosts.where("id % 2 != 0").limit(5)
    @latestPost = Post.last

    # if session[:user_id]
    #   @user = User.find(session[:user_id])
    # end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :feature_text, :user_id, :category_id, :status, :fonticon, :postimageurl, :featured)
    end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    if @user = login(params[:email], params[:password])
      redirect_back_or_to(:users, notice: 'Login successful')
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(:users, notice: 'Logged out!')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = {
      filter_html: true,
      hard_wrap: true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true, 
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :fonticon %><br>
    <%= f.text_field :fonticon %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Fonticon</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.fonticon %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Fonticon:</strong>
  <%= @category.fonticon %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/home/index.html.erb
<!-- ****** Promo ****** --> 
<section id="promo" class="promo section home-offset-header has-pattern">
  <div class="container">
    <div class="row">
      <div class="overview col-md-12 col-sm-12 col-xs-12">
        <% @categories.limit(4).order('created_at ASC').each do |c| %>
        <h2 class="title text-center sr-only">Features</h2>
        <div class="item col-md-3 col-sm-6 col-xs-12 text-center">

          <div class="icon feature_icon">
            <i class="fa fa-<%= c.fonticon %>"></i>                
          </div><!--//icon-->
          <br>
          <div class="content feature_border card_post">
            <h1 class="title"><%= link_to c.name %></h1>
            <hr>
            <div class="text-left">
              <% c.posts.limit(4).order('updated_at DESC').each do |p| %>

                <p>
                  <!-- <span class="fa-stack fa"> -->
                    <!-- <i class="fa fa-circle fa-stack-2x"></i> -->
                    <i class="fa fa-<%= c.fonticon %> blue">  </i>
                  <!-- </span> -->
                  <%= link_to p.title, post_path(p) %>
                </p>

              <% end -%>
            </div>
            <button class="modal-trigger btn btn-link" data-toggle="modal" data-target="#feature-modal-1"><%= link_to "More", posts_path %></button>
          </div><!--//content-->               
        </div><!--//item-->

      <% end -%>   
      </div><!--//overview-->                                           
    </div><!--//row-->
  </div><!--//container-->
</section><!--//promo-->


<!-- ****** Featured Posts ****** --> 
<section id="features" class="features section">
  <div class="container">
    <div class="row">

    </div><!--//row-->
  </div><!--//container-->
</section><!--//features-->


<section class="promo has-pattern">
  <div class="container">
    <div class="row">
      <!-- <div class="overview col-md-12 col-sm-12 col-xs-12"> -->
        <h2 class="recent_title text-center">Recent Posts</h2>        
      <!-- </div><!--//overview-->
    </div><!--//row-->
  </div><!--//container-->
</section><!--//promo-->

<!-- ******Recent Posts****** --> 
    <section id="recent" class="recent section">
        <div class="container">
            <div class="row">

                <div class="faq-col col-md-6 col-sm-6 col-xs-12">
                   <% @oddPosts.each do |op| %>
                    <div class="item card_body">
                        <h3 class="question card_title">

                          <span class="fa-stack fa">
                            <i class="fa fa-circle fa-stack-2x"></i>
                            <i class="fa fa-<%= op.category.fonticon %> fa-stack-1x fa-inverse"></i>
                          </span>

                          <span class="small pull-right">
                            <%= op.updated_at.strftime("%B %d, %Y") %>
                          </span>
                          <%= link_to op.title, post_path(op), class: "title"%>
                        </h3>

                        <% if op.body.length <= 1000 %>
                          <span class="answer"><%= markdown(op.body) %></span>
                        <% else %>
                          <span class="answer"><%= markdown(op.featuretext) %></span>
                        <% end %>
                        <button class="modal-trigger btn btn-link" data-toggle="modal" data-target="#feature-modal-1"><%= link_to "Read more", post_path(op) %></button>
                    </div><!--//item-->
                  <% end -%>
                </div><!--//faq-col-->

                <div class="faq-col col-md-6 col-sm-6 col-xs-12">
                  <p>even posts</p>

                </div><!--//recent-col-->
            </div><!--//row-->

        </div><!--//container-->
    </section><!--//recent posts-->
            <section class="promo has-pattern">
              <div class="container">
                <div class="row">
                  <!-- <div class="overview col-md-12 col-sm-12 col-xs-12"> -->
                    <h3 class=" text-center">posts</h3>        
                  <!-- </div><!--//overview-->
                </div><!--//row-->
              </div><!--//container-->
            </section><!--//promo-->
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>tim ludi | diligent agility</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render '/shared/header' %>
      
  <%= yield %>

  <% if @home %>
    <%= render '/shared/footer' %>
  <% end -%>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :feature_text %><br>
    <%= f.text_area :feature_text %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.number_field :category_id %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.number_field :status %>
  </div>
  <div class="field">
    <%= f.label :fonticon %><br>
    <%= f.text_field :fonticon %>
  </div>
  <div class="field">
    <%= f.label :postimageurl %><br>
    <%= f.text_field :postimageurl %>
  </div>
  <div class="field">
    <%= f.label :featured %><br>
    <%= f.number_field :featured %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Feature text</th>
      <th>User</th>
      <th>Category</th>
      <th>Status</th>
      <th>Fonticon</th>
      <th>Postimageurl</th>
      <th>Featured</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= post.feature_text %></td>
        <td><%= post.user_id %></td>
        <td><%= post.category_id %></td>
        <td><%= post.status %></td>
        <td><%= post.fonticon %></td>
        <td><%= post.postimageurl %></td>
        <td><%= post.featured %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<p>
  <strong>Feature text:</strong>
  <%= @post.feature_text %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user_id %>
</p>

<p>
  <strong>Category:</strong>
  <%= @post.category_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @post.status %>
</p>

<p>
  <strong>Fonticon:</strong>
  <%= @post.fonticon %>
</p>

<p>
  <strong>Postimageurl:</strong>
  <%= @post.postimageurl %>
</p>

<p>
  <strong>Featured:</strong>
  <%= @post.featured %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/shared/_categories.html.erb
<div class="side_links">

  <% if session[:user_id] %>
    <p class="user_name">Logged in | 
    <%= link_to 'Log Out', logout_path %>
    <br>
    <%= link_to 'New Post', new_post_path %></p>
    <%= link_to 'Private Posts', "#" %>
  <% end -%>
  <br>
  <% if @current_public_post %>
    <%= link_to "Latest_post", post_path(@current_public_post) %></br>
  <% end %>
</div>

<h3>Categories  
<span>
<% if logged_in? %>
  <%= link_to ">> New category", new_category_path, :class => "small" %>
<% end -%>
</span>
</h3>
<hr>
<% @categories.each do |c| %>
  <div class="category">
    <h5>
      <span class="fa-stack fa">
        <i class="fa fa-circle fa-stack-2x"></i>
        <i class="fa fa-<%= c.fonticon %> fa-stack-1x fa-inverse"></i>
      </span>
        <span class="catName"><%= c.name %></span>
        <span class="badge">
          <%= c.posts.count %>
        </span>
    </h5>
    <% c.posts.each do |category_post| %>
      <ul>
        <li><%= link_to category_post.title, post_path(category_post) %></li>  
      </ul>
    <% end -%>
  </div>
<% end -%>

app/views/shared/_footer.html.erb
<footer class="footer">
    <div class="container">
      <div class="footer">
        <div class="content">

          <p><%= link_to image_tag("logo.png", width: "70", class: "logo"), "http://www.diligentagility.com" %> <span class="ftext"> <span class="dagreen">diligent</span><span class="dablue">agility</span><small class="copyright"> - timludi - Copyright &copy; 2010 - 2015</small></span></p>

        </div>
      </div>
    </div>
</footer>

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, :method => :post do %>
  <div class="field">
    <%= label_tag :email %><br />
    <%= text_field_tag :email %>
  </div>
  <div class="field">
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
  </div>
  <div class="actions">
    <%= submit_tag "Login" %>
  </div>
<% end %>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<!-- # app/views/user_sessions/new.html.erb -->
<h1>Login</h1>

<%= render 'form' %>

<%= link_to 'Back', user_sessions_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
     <%= f.label :password %><br />
     <%= f.password_field :password %>
  </div>
  <div class="field">
     <%= f.label :password_confirmation %><br />
     <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Crypted password</th>
      <th>Salt</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.crypted_password %></td>
        <td><%= user.salt %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Crypted password:</strong>
  <%= @user.crypted_password %>
</p>

<p>
  <strong>Salt:</strong>
  <%= @user.salt %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>